### PR TITLE
Updated fr (French) translation

### PR DESCRIPTION
**Pull request by bennok**
Commit made via [Stringlate](https://lonamiwebs.github.io/stringlate/)

### CODE REVIEW

**Comment by bennok** [comment]
I am new to this. I am not sure about one and another translation. But I am very confident of all the strings I could identify while using JTT on my phone. I would enjoy very much having my contribution appear in some of the next updates :)

**Comment by bennok** [comment]
I am new to this. I am not sure about one and another translation. But I am very confident of all the strings I could identify while using JTT on my phone. I would enjoy very much having my contribution appear in some of the next updates :)

**Comment by aragaer** [comment]
Thanks!
I'm currently on vacation, but I will review your pull request and merge it as soon as I'm back.

**Comment by aragaer** [comment]
Finally found some time to check it. Your commit adds french translation - that is correct. But it's based on wrong (stale) branch. Because of this the patch doesn't apply (a lot of conflicts). I have solved this by cherry-picking the commit. Not all strings are translated. It's missing all the string arrays:
- hour_name_option_names (default/romaji/hiragana)
- hour (The Cock, The Dog etc)
- hour_of (long hour names - Hour of the Cock etc)
- quarter (first quarter, second quarter, third quarter, fourth quarter)
- theme_names (Translucent/Dark/Light)
- widget_theme_names (same as above)

**Pull request closed without merging**
